# Generated by Django 4.2 on 2023-05-14 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PollingStation",
            fields=[
                ("station_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("scounty", models.CharField(max_length=100)),
                ("sconstituency", models.CharField(max_length=100)),
                ("sward", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("age", models.IntegerField()),
                ("first_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                ("id_number", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
                ("last_name", models.CharField(max_length=50)),
                (
                    "occupation",
                    models.CharField(
                        choices=[("C", "Casual"), ("F", "Formal")],
                        max_length=1,
                        verbose_name="occupation",
                    ),
                ),
                (
                    "special_condition",
                    models.CharField(
                        choices=[
                            ("E", "Expectant/Mothers"),
                            ("S", "Sick"),
                            ("D", "Disabled"),
                        ],
                        max_length=1,
                        verbose_name="condition",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                ("voter_id", models.IntegerField(primary_key=True, serialize=False)),
                ("service_time", models.FloatField(default=0.0)),
                ("waiting_time", models.FloatField(default=0.0)),
                ("ticket_no", models.CharField(max_length=500)),
                ("voted", models.BooleanField(default=False)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("vote_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.voter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("length", models.IntegerField(verbose_name=0)),
                ("queue_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.pollingstation",
                    ),
                ),
                ("voters", models.ManyToManyField(to="core.voter")),
            ],
        ),
        migrations.AddField(
            model_name="pollingstation",
            name="voters",
            field=models.ManyToManyField(to="core.voter"),
        ),
    ]
