# Generated by Django 4.2 on 2023-05-20 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pollingstation",
            name="constituency",
        ),
        migrations.RemoveField(
            model_name="pollingstation",
            name="county",
        ),
        migrations.AddField(
            model_name="consituency",
            name="county",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.county"
            ),
        ),
        migrations.AddField(
            model_name="ward",
            name="constituency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.consituency",
            ),
        ),
    ]
