# Generated by Django 4.2 on 2023-05-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="profile_pics"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="special_condition",
            field=models.CharField(
                choices=[("E", "Expectant/Mothers"), ("S", "Sick"), ("D", "Disabled")],
                max_length=1,
                null=True,
                verbose_name="condition",
            ),
        ),
        migrations.AlterField(
            model_name="voter",
            name="ticket_no",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
