# Generated by Django 4.2 on 2023-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_userprofile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="special_condition",
            field=models.CharField(
                choices=[
                    ("E", "Expectant/Mothers"),
                    ("S", "Sick"),
                    ("D", "Disabled"),
                    ("N", "None"),
                ],
                max_length=1,
                null=True,
                verbose_name="condition",
            ),
        ),
    ]
