# Generated by Django 4.2 on 2023-05-21 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_pollingstation_constituency_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pollingstation",
            old_name="station_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="queue",
            old_name="queue_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="voter_id",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="pollingstation",
            name="location",
        ),
        migrations.RemoveField(
            model_name="pollingstation",
            name="ward",
        ),
        migrations.CreateModel(
            name="PollingCenter",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "ward",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ward",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pollingstation",
            name="center",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.pollingcenter",
            ),
        ),
    ]
