# Generated by Django 4.2 on 2023-05-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_userprofile_special_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="length",
            field=models.IntegerField(),
        ),
    ]
