# Generated by Django 4.2 on 2023-05-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pollingstation_voter_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pollingstation",
            name="id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pollingstation",
            name="voter_no",
            field=models.IntegerField(default=1),
        ),
    ]
