# Generated by Django 4.2 on 2023-05-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_queue_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="image",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.IntegerField(null=True),
        ),
    ]
