# Generated by Django 4.2 on 2023-05-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_pollingstation_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Consituency",
            new_name="Constituency",
        ),
    ]
