# Generated by Django 4.0.3 on 2023-05-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_consituency_constituency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='length',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='voters',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='station',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='ticket_no',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='waiting_time',
        ),
        migrations.AddField(
            model_name='vote',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pollingstation'),
        ),
        migrations.AddField(
            model_name='voter',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pollingcenter'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.TimeField()),
                ('stop', models.TimeField()),
                ('voters', models.ManyToManyField(related_name='voters', to='core.voter')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pollingstation')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter', to='core.voter')),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='tickets',
            field=models.ManyToManyField(related_name='queues', to='core.ticket'),
        ),
        migrations.AddField(
            model_name='voter',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='core.ticket'),
        ),
        migrations.AddField(
            model_name='voter',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.timeslot'),
        ),
    ]
