# Generated by Django 4.0.3 on 2023-05-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ticket_id_alter_vote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
