# Generated by Django 4.0.3 on 2023-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_queue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingcenter',
            name='voter_no',
            field=models.IntegerField(default=0),
        ),
    ]
