# Generated by Django 4.0.3 on 2023-06-10 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pollingcenter_voter_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
