# Generated by Django 4.0.3 on 2023-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_voter_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(choices=[('CH', 'Casual Hard'), ('CS', 'Casual Soft'), ('F', 'Formal')], max_length=2, null=True, verbose_name='occupation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='special_condition',
            field=models.CharField(choices=[('S', 'Special'), ('N', 'None')], max_length=1, null=True, verbose_name='condition'),
        ),
    ]
