# Generated by Django 4.0.3 on 2023-06-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_userprofile_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='waiting_time',
            field=models.FloatField(default=0.0),
        ),
    ]
