# Generated by Django 4.0.3 on 2023-06-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_queue_waiting_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('S', 'Special'), ('A', 'On Time'), ('B', 'Out of Time')], max_length=1, verbose_name='condition')),
            ],
        ),
    ]
