# Generated by Django 4.0.3 on 2023-06-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tickettype'),
            preserve_default=False,
        ),
    ]
