# Generated by Django 4.0.3 on 2023-06-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_ticket_type_delete_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ticket',
            name='queue_number',
            field=models.IntegerField(default=1),
        ),
    ]
