# Generated by Django 4.0.3 on 2023-06-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_constituency_county_alter_pollingcenter_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='current_voter_st',
            field=models.FloatField(default=0.0),
        ),
    ]
